# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the GNU Affero General Public License (AGPL).
# See License-AGPL.txt in the project root for license information.

packages:
  - name: app
    type: go
    deps:
      - components/common-go:lib
    srcs:
      - go.mod
      - go.sum
      - "**/*.go"
    env:
      - CGO_ENABLED=0
    config:
      packaging: app
      buildCommand:
        [
          "go",
          "build",
          "-trimpath",
          "-ldflags",
          "-buildid= -w -s -X 'github.com/gitpod-io/gitpod/kots-config-check/registry/cmd.Version=commit-${__git_commit}'",
        ]
  - name: docker
    type: docker
    deps:
      - :app
    argdeps:
      - imageRepoBase
    config:
      dockerfile: leeway.Dockerfile
      metadata:
        helm-component: kots-config-check.registry
      image:
        - ${imageRepoBase}/kots-config-check/registry:${version}
        - ${imageRepoBase}/kots-config-check/registry:commit-${__git_commit}
